services:
  n-thaismart-web:
    image: ${DOCKER_REGISTRY-}nthaismartweb
    build:
      context: .
      dockerfile: NThaiSmartWeb/Dockerfile
    ports:
      - "5201:5201"  # Host:Container
    environment:
      - ASPNETCORE_URLS=http://+:5201
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Bangkok